spring.application.name=order-service
server.port=8083

services.user.primary-url=${USER_SERVICE_URL:http://user-service:8080/users/1}
services.user.fallback-url=${USER_SERVICE_FALLBACK_URL:http://localhost:8081/users/1}

services.product.primary-url=${PRODUCT_SERVICE_URL:http://product-service:8080/products/101}
services.product.fallback-url=${PRODUCT_SERVICE_FALLBACK_URL:http://localhost:8082/products/101}

services.payment.primary-url=${PAYMENT_SERVICE_URL:http://payment-service:5001/pay}
services.payment.fallback-url=${PAYMENT_SERVICE_FALLBACK_URL:http://localhost:5001/pay}
