spring.application.name=order-service
server.port=8083
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/microservices_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always

services.user.primary-base-url=${USER_SERVICE_URL:http://user-service:8081/users}
services.user.fallback-base-url=${USER_SERVICE_FALLBACK_URL:http://localhost:8081/users}

services.product.primary-base-url=${PRODUCT_SERVICE_URL:http://product-service:8082/products}
services.product.fallback-base-url=${PRODUCT_SERVICE_FALLBACK_URL:http://localhost:8082/products}

services.payment.primary-url=${PAYMENT_SERVICE_URL:http://payment-service:5001/pay}
services.payment.fallback-url=${PAYMENT_SERVICE_FALLBACK_URL:http://localhost:5001/pay}

services.notification.primary-url=${NOTIFICATION_SERVICE_URL:http://notification-service:5002/notify}
services.notification.fallback-url=${NOTIFICATION_SERVICE_FALLBACK_URL:http://localhost:5002/notify}

services.analytics.primary-url=${ANALYTICS_SERVICE_URL:http://analytics-service:5003/analytics}
services.analytics.fallback-url=${ANALYTICS_SERVICE_FALLBACK_URL:http://localhost:5003/analytics}
